
const actionTypes = {
    LOGIN_PROGRESS : 'LOGIN_PROGRESS',
    LOGIN_SUCCEED : 'LOGIN_SUCCEED',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGIN_ERROR_ALERT : 'LOGIN_ERROR_ALERT',

    SIGNUP_PROGRESS : 'SIGNUP_PROGRESS',
    SIGNUP_SUCCEED : 'SIGNUP_SUCCEED',
    SIGNUP_ERROR : 'SIGNUP_ERROR',
    SIGNUP_ERROR_ALERT : 'SIGNUP_ERROR_ALERT',

    LOGOUT_SUCCEED : 'LOGOUT_SUCCEED',

    ALL_REGISTERED_USERS: 'ALL_REGISTERED_USERS',
    ALL_REGISTERED_USERS_REQUEST: 'ALL_REGISTERED_USERS_REQUEST',
    EMPTY_STORE : 'EMPTY_STORE',

    CHAT_WITH: 'CHAT_WITH',
    CURRENT_USER: 'CURRENT_USER',

    MESSAGE_RETRIVE_REQUEST: 'MESSAGE_RETRIVE_REQUEST',
    MESSAGE_RETRIVE_SUCCEED: 'MESSAGE_RETRIVE_SUCCEED',
    MESSAGE_RETRIVE_REQUEST_WITHLOADER: 'MESSAGE_RETRIVE_REQUEST_WITHLOADER',
    NO_MESSAGE_DO_NOTHING: 'NO_MESSAGE_DO_NOTHING'
    
}
export default actionTypes;